spring:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.jdbc.time_zone: Europe/Vienna
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_ACTION}
      dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  messages:
    encoding: UTF-8
  jackson:
    time-zone: Europe/Vienna
---
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.jdbc.time_zone: Europe/Vienna
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_ACTION}
      dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  messages:
    encoding: UTF-8
  jackson:
    time-zone: Europe/Vienna