create sequence scanned_location_id_seq;

create table address
(
    id          bigint generated by default as identity
        primary key,
    city        varchar(255),
    country     varchar(255),
    created_at  timestamp(6),
    modified_at timestamp(6),
    street      varchar(255),
    zip_code    varchar(255)
);

create table appuser
(
    id            bigint generated by default as identity
        primary key,
    active        boolean      not null,
    created_at    timestamp(6),
    email         varchar(255) not null
        constraint ukhcij6hlq32eras7xlmvbx2sbm
            unique,
    modified_at   timestamp(6),
    password      varchar(255) not null,
    persist_login boolean      not null
);

create table owner
(
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp(6),
    first_name         varchar(255) not null,
    last_name          varchar(255) not null,
    modified_at        timestamp(6),
    phone              varchar(255) not null,
    address_id         bigint
        constraint ukbdjoy6x5e3odg02d6guuilx2
            unique
        constraint fkda9u2g6vwepwq8fb26hiyxcdv
            references address,
    user_id            bigint       not null
        constraint uk8nrpb1o74o0ol4ejcymyffplg
            unique
        constraint fkf5otak60pssxgg06oqgvogl7l
            references appuser,
    is_address_visible boolean default false
);


create table pet
(
    id          bigint generated by default as identity
        primary key,
    breed       varchar(255),
    created_at  timestamp(6),
    modified_at timestamp(6),
    name        varchar(255) not null,
    photo_url   varchar(255),
    sex         varchar(255)
        constraint pet_sex_check
            check ((sex)::text = ANY ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying])::text[])),
    owner_id    bigint       not null
        constraint fk7qfti9yba86tgfe9oobeqxfxg
            references owner,
    birth_year  integer
);

create table nfc_tag
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6),
    modified_at timestamp(6),
    status      varchar(255) not null
        constraint nfc_tag_status_check
            check ((status)::text = ANY
                   ((ARRAY ['AVAILABLE'::character varying, 'CLAIMED'::character varying, 'UNCLAIMED'::character varying])::text[])),
    tag_id      varchar(255) not null
        constraint uklmcitjbdb95p5utg4lmxvtybx
            unique,
    pet_id      bigint
        constraint ukjsb9iw66fkdfnrkyypy1fjhov
            unique
        constraint fk5ouo4aic7mkj0erhpbqihwhnr
            references pet
);

create table scanned_location
(
    id         bigint default nextval('scanned_location_id_seq'::regclass) not null
        primary key,
    latitude   double precision,
    longitude  double precision,
    scanned_at timestamp,
    pet_id     bigint                                                      not null
        constraint fk_pet
            references pet
);

create table forgot_password_token
(
    id         bigint generated always as identity
        primary key,
    token      varchar(255),
    user_id    bigint not null
        constraint fk_user
            references appuser,
    created_at timestamp
);
