CREATE TABLE address
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country     VARCHAR(255),
    city        VARCHAR(255),
    zip_code    VARCHAR(255),
    street      VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE appuser
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    active        BOOLEAN                                 NOT NULL,
    persist_login BOOLEAN                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    modified_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appuser PRIMARY KEY (id)
);

CREATE TABLE forgot_password_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255),
    user_id    BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_forgot_password_token PRIMARY KEY (id)
);

CREATE TABLE nfc_tag
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_id      VARCHAR(255)                            NOT NULL,
    pet_id      BIGINT,
    status      VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_nfc_tag PRIMARY KEY (id)
);

CREATE TABLE owner
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name         VARCHAR(255)                            NOT NULL,
    last_name          VARCHAR(255)                            NOT NULL,
    phone              VARCHAR(255)                            NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    address_id         BIGINT,
    is_address_visible BOOLEAN                                 NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    modified_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_owner PRIMARY KEY (id)
);

CREATE TABLE pet
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    breed       VARCHAR(255),
    birth_year  INTEGER                                 NOT NULL,
    sex         VARCHAR(255),
    photo_url   VARCHAR(255),
    owner_id    BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_pet PRIMARY KEY (id)
);

CREATE TABLE scan_event
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_id        BIGINT                                  NOT NULL,
    consent_given BOOLEAN                                 NOT NULL,
    scanned_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    locale        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_scan_event PRIMARY KEY (id)
);

CREATE TABLE scanned_location
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    scan_event_id BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_scanned_location PRIMARY KEY (id)
);

ALTER TABLE appuser
    ADD CONSTRAINT uc_appuser_email UNIQUE (email);

ALTER TABLE nfc_tag
    ADD CONSTRAINT uc_nfc_tag_petid UNIQUE (pet_id);

ALTER TABLE nfc_tag
    ADD CONSTRAINT uc_nfc_tag_tagid UNIQUE (tag_id);

ALTER TABLE owner
    ADD CONSTRAINT uc_owner_addressid UNIQUE (address_id);

ALTER TABLE owner
    ADD CONSTRAINT uc_owner_userid UNIQUE (user_id);

ALTER TABLE scanned_location
    ADD CONSTRAINT uc_scanned_location_scan_event UNIQUE (scan_event_id);

ALTER TABLE forgot_password_token
    ADD CONSTRAINT FK_FORGOT_PASSWORD_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES appuser (id);

ALTER TABLE nfc_tag
    ADD CONSTRAINT FK_NFC_TAG_ON_PETID FOREIGN KEY (pet_id) REFERENCES pet (id);

ALTER TABLE owner
    ADD CONSTRAINT FK_OWNER_ON_ADDRESSID FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE owner
    ADD CONSTRAINT FK_OWNER_ON_USERID FOREIGN KEY (user_id) REFERENCES appuser (id);

ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_OWNERID FOREIGN KEY (owner_id) REFERENCES owner (id);

ALTER TABLE scanned_location
    ADD CONSTRAINT FK_SCANNED_LOCATION_ON_SCAN_EVENT FOREIGN KEY (scan_event_id) REFERENCES scan_event (id);

ALTER TABLE scan_event
    ADD CONSTRAINT FK_SCAN_EVENT_ON_PET FOREIGN KEY (pet_id) REFERENCES pet (id);