ALTER TABLE scanned_location
    DROP CONSTRAINT fk_pet;

CREATE TABLE scan_event
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pet_id        BIGINT                                  NOT NULL,
    consent_given BOOLEAN                                 NOT NULL,
    scanned_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    locale        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_scan_event PRIMARY KEY (id)
);

ALTER TABLE scanned_location
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE scanned_location
    ADD scan_event_id BIGINT;

ALTER TABLE scanned_location
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE scanned_location
    ALTER COLUMN scan_event_id SET NOT NULL;

ALTER TABLE scanned_location
    ADD CONSTRAINT uc_scanned_location_scan_event UNIQUE (scan_event_id);

ALTER TABLE scanned_location
    ADD CONSTRAINT FK_SCANNED_LOCATION_ON_SCAN_EVENT FOREIGN KEY (scan_event_id) REFERENCES scan_event (id);

ALTER TABLE scan_event
    ADD CONSTRAINT FK_SCAN_EVENT_ON_PET FOREIGN KEY (pet_id) REFERENCES pet (id);

ALTER TABLE scanned_location
    DROP COLUMN pet_id;

ALTER TABLE scanned_location
    DROP COLUMN scanned_at;

ALTER TABLE pet
    ALTER COLUMN birth_year SET NOT NULL;

CREATE SEQUENCE IF NOT EXISTS scanned_location_id_seq;
ALTER TABLE scanned_location
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE scanned_location
    ALTER COLUMN id SET DEFAULT nextval('scanned_location_id_seq');

ALTER SEQUENCE scanned_location_id_seq OWNED BY scanned_location.id;

ALTER TABLE owner
    ALTER COLUMN is_address_visible SET NOT NULL;