services:
  app:
    container_name: pawsitive_backend_prod
    build:
      context: .
      dockerfile: Dockerfile
    image: dezsoab/springboot_backend:prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          memory: ${APP_MEMORY_LIMIT}
        reservations:
          memory: ${APP_MEMORY_RESERVATION}
  mysql:
    image: mysql:8.0
    container_name: pawsitive_mysql_prod
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=pawsitive_PROD
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: ${MYSQL_MEMORY_LIMIT}
        reservations:
          memory: ${MYSQL_MEMORY_RESERVATION}

volumes:
  mysql_data:
    driver: local
