version: '3.8'
services:
  app:
    image: dezsoab/springboot_backend:test
    container_name: pawsitive_backend_test
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pawsitive_TEST
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:8.0
    container_name: pawsitive_mysql_test
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pawsitive_TEST
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent storage
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  mysql_data:  # Named volume (stores data persistently)
