services:
  app:
    container_name: pawsitive_backend_test
    build:
      context: .
      dockerfile: Dockerfile
    image: dezsoab/springboot_backend:test
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          memory: ${APP_MEMORY_LIMIT}
        reservations:
          memory: ${APP_MEMORY_RESERVATION}
