services:
  app:
    container_name: pawsitive_backend_test
    build:
      context: .
      dockerfile: Dockerfile
    image: dezsoab/springboot_backend:test
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pawsitive_TEST
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: pawsitive_mysql_test
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=pawsitive_TEST
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local