export enum backendRoutes {
  AUTH = "auth",
  REGISTER = AUTH + "/register",
  LOGIN = AUTH + "/login",
  LOGOUT = AUTH + "/logout",
  ISAUTHENTICATED = AUTH + "/authenticated",
  PET = "pet",
  NFCTAG = "nfcTag",
  CONTACTUS = "mail/emailContactUs",
  ISAUTHENTICATEDUSEROWNEROFPET = "owner/isAuthenticatedUserOwnerOfPet",
  PROFILE = "profile",
  UPDATEPROFILE = "profile/update",
  PRESIGNEDPETURL = "s3/presigned-url?fileName=",
  PETINFORMATION = PET + "/information",
  LOCATION = "location",
  SCANNEDLOCATION = LOCATION + "/scanned",
  USER = "user",
  FORGOT_PASSWORD = USER + "/forgot",
}
