export enum navigationRoutes {
  ABOUT = "/about",
  HOME = "/home",
  CONTACT = "/contact",
  SHOP = "https://shop.pawsitivecollar.com",
  PRIVACY = "https://shop.pawsitivecollar.com/policies/privacy-policy",
  TERMS = "https://shop.pawsitivecollar.com/policies/terms-of-service",
  FAQs = "/FAQs",
  INSTA = "https://www.instagram.com/pawsitivecollar_/",
  FACEBOOK = "https://www.facebook.com/profile.php?id=61579176221351",
  LOGOUT = "/authenticate/logout",
  PROFILE = "/profile",
  AUTH = "/authenticate",
  PET = "/pet",
  NOTFOUND = "/404",
  IMPRESSUM = "https://shop.pawsitivecollar.com/policies/legal-notice",
}
