export enum navigationRoutes {
  ABOUT = "/about",
  HOME = "/home",
  CONTACT = "/contact",
  SHOP = "https://shop.pawsitivecollar.com",
  PRIVACY = "/privacy-policy",
  TERMS = "/terms-and-conditions",
  FAQs = "/FAQs",
  INSTA = "/insta",
  FACEBOOK = "/facebook",
  LOGOUT = "/authenticate/logout",
  PROFILE = "/profile",
  AUTH = "/authenticate",
  PET = "/pet",
  NOTFOUND = "/404",
}
