services:
  nextjs_prod:
    container_name: nextjs_prod
    image: dezsoab/nextjs_prod
    build: ./
    platform: linux/amd64
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  nginx:
    container_name: nginx
    image: dezsoab/nginx
    build: ./nginx
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
      
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email binderdezso97@gmail.com -d pawsitivecollar.com --agree-tos