name: Docker Deployment

on:
  push:
    branches:
      - docker-setup

jobs:
  Docker-CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        working-directory: ./frontend/ui
        run: |
          docker compose build
          docker compose push

      - name: SSH into production server and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/pawsitivecollar.com/Pawsitive/frontend/ui
            docker compose down
            docker compose pull
            docker compose up -d
