name: Continous Deployment on Prod Server

on:
  pull_request:
    branches:
      - prod
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: "cd /var/www/pawsitivecollar.com && ./auto_deploy.sh"
