name: Docker PROD Deployment

on:
  pull_request:
    branches:
      - prod
    types: [closed]

jobs:
  Deploy-to-PROD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build the application
        working-directory: ./backend/pawsitive
        run: |
          ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        working-directory: ./backend/pawsitive
        run: |
          IMAGE_TAG=dezsoab/springboot_backend:prod-${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: SSH into PROD server and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST_PROD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            COMPOSE_DIR="/root/server"
            COMPOSE_FILE="docker-compose.prod.yml"
            IMAGE_TAG="dezsoab/springboot_backend:prod-${{ github.sha }}"

            # Ensure the directory exists
            if [ ! -d "$COMPOSE_DIR" ]; then
              echo "Error: Directory $COMPOSE_DIR does not exist!"
              exit 1
            fi

            cd $COMPOSE_DIR

            # Ensure the compose file exists
            if [ ! -f "$COMPOSE_FILE" ]; then
              echo "Error: $COMPOSE_FILE not found in $COMPOSE_DIR!"
              exit 1
            fi

            # Pull the latest image
            docker pull $IMAGE_TAG

            # Update docker-compose file with new image tag
            sed -i 's|image: dezsoab/springboot_backend:prod.*|image: '$IMAGE_TAG'|' $COMPOSE_FILE

            docker-compose -f $COMPOSE_FILE down
            docker-compose -f $COMPOSE_FILE up -d --force-recreate
