name: Docker Test Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - test
    types: [closed]

jobs:
  Docker-CD-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build the application
        working-directory: ./backend/pawsitive
        run: |
          ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        working-directory: ./backend/pawsitive
        run: |
          IMAGE_TAG=dezsoab/springboot_backend:test-${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: SSH into test server and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST_TEST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to the Docker Compose directory
            cd /server

            # Pull the latest image
            docker pull dezsoab/springboot_backend:test-${{ github.sha }}

            # Update the app service with the new image tag in docker-compose.yml
            sed -i 's|image: dezsoab/springboot_backend:test.*|image: dezsoab/springboot_backend:test-${{ github.sha }}|' docker-compose.test.yml

            # Restart the application
            docker-compose down
            docker-compose up -d --force-recreate
