name: Docker Test Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - test
    types: [closed]

jobs:
  Docker-CD-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build the application
        working-directory: ./backend
        run: |
          ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        working-directory: ./backend
        run: |
          docker build -t dezsoab/springboot_backend:test .
          docker push dezsoab/springboot_backend:test

      - name: SSH into test server and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST_TEST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/pawsitivecollar.com/Pawsitive/backend
            docker compose -f docker-compose.test.yml down
            docker compose -f docker-compose.test.yml pull
            docker compose -f docker-compose.test.yml up -d
            docker image prune -f
            docker system prune -af
