name: Docker Test Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - test
    types: [closed]

jobs:
  Docker-CD-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build the application
        working-directory: ./backend/pawsitive
        run: |
          ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        working-directory: ./backend/pawsitive
        run: |
          IMAGE_TAG=dezsoab/springboot_backend:test-${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: SSH into test server and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST_TEST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Define variables
            CONTAINER_NAME="springboot_backend"
            IMAGE_TAG="dezsoab/springboot_backend:test-${{ github.sha }}"

            # Stop and remove old container (if exists)
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            # Pull latest image
            docker pull $IMAGE_TAG

            # Run container with correct settings
            docker run -d \
              --name $CONTAINER_NAME \
              -p 8080:8080 \
              --restart unless-stopped \
              -e SPRING_PROFILES_ACTIVE=test \
              $IMAGE_TAG

            # Cleanup old images
            docker image prune -af
