name: Docker TEST Deployment

on:
  pull_request:
    branches:
      - test
    types: [closed]

jobs:
  Deploy-to-TEST:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if backend has changed
        id: backend-check
        run: |
          echo "Checking for backend changes..."
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          echo "Base SHA: $BASE_SHA"
          echo "Head SHA: $HEAD_SHA"
          CHANGED=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" | grep '^backend/' || true)
          if [ -z "$CHANGED" ]; then
            echo "No backend changes detected. Skipping deployment."
            echo "should_skip=true" >> $GITHUB_OUTPUT
          else
            echo "Backend changes detected:"
            echo "$CHANGED"
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if no backend changes
        if: steps.backend-check.outputs.should_skip == 'true'
        run: |
          echo "Skipping rest of workflow..."
          exit 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build the application
        working-directory: ./backend/pawsitive
        run: |
          ./mvnw clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        working-directory: ./backend/pawsitive
        run: |
          IMAGE_TAG=dezsoab/springboot_backend:test-${{ github.sha }}
          docker build --no-cache -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: SSH into TEST server and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST_TEST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            COMPOSE_DIR="/root/server"
            COMPOSE_FILE="docker-compose.test.yml"
            IMAGE_TAG="dezsoab/springboot_backend:test-${{ github.sha }}"

            # Ensure the directory exists
            if [ ! -d "$COMPOSE_DIR" ]; then
              echo "Error: Directory $COMPOSE_DIR does not exist!"
              exit 1
            fi

            cd $COMPOSE_DIR

            # Ensure the compose file exists
            if [ ! -f "$COMPOSE_FILE" ]; then
              echo "Error: $COMPOSE_FILE not found in $COMPOSE_DIR!"
              exit 1
            fi

            # Pull the latest image
            docker pull $IMAGE_TAG

            # Update docker-compose file with new image tag
            sed -i 's|image: dezsoab/springboot_backend:test.*|image: '$IMAGE_TAG'|' $COMPOSE_FILE

            docker-compose -f $COMPOSE_FILE down
            docker system prune -f
            docker-compose -f $COMPOSE_FILE up -d --force-recreate
